### PR TITLE
offset_from and offset_to should be bytes offsets

### PR DESCRIPTION
**Pull request by PSeitz**

### CODE REVIEW

**Comment by PSeitz** [comment]
untested btw., I just edited it in the github browser

**Comment by jiegec** [comment]
@carmel Could you check whether this change fixes issue https://github.com/tantivy-search/tantivy/issues/1134?

**Comment by jiegec** [comment]
The fix is included in release v0.5.1

**Comment by carmel** [comment]
@jiegec Thans for your attention, this has been solved. Nice!

**Pull request merged**
